config/routes.rb
Rails.application.routes.draw do

  get '/coding-challenges', to:"kata#index"

  get '/game-plan', to:"kata#game_plan"

  get '/account-info', to:"user#account_info"

  post '/coding-challenges', to:"kata#create"

  post '/submit-answer', to:"kata#submit"

  root "users#signup"

  get "/signup", to: "users#signup"

  post "/signup", to:"users#create"

  get '/login', to:"users#login", as:"home"

  post "/login", to:"users#attempt_login"

  delete '/logout', to: "users#logout", as:"logout"

  resources :resets, only: [:new, :edit, :create, :update]

end

app/models/katum.rb
class Katum < ActiveRecord::Base
  has_many :users,  through: :socials 
  has_many :socials, dependent: :destroy
end

app/models/social.rb
class Social < ActiveRecord::Base
  belongs_to :user
  belongs_to :katum
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence:true, uniqueness:true
  validates :email, presence:true

  has_many :kata,  through: :socials 
  has_many :socials, dependent: :destroy

  def generate_password_reset_token!
   update(password_reset_token: SecureRandom.urlsafe_base64(48))
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def confirm_logged_in
    unless session[:user_id]
      redirect_to login_path, alert: "Please log in!"
    end
  end

  def prevent_login_signup
    if session[:user_id]
      redirect_to "/", notice: "You are already logged in!"
    end
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by_id(session[:user_id])
  end

  helper_method :current_user
end

app/controllers/kata_controller.rb
class KataController < ApplicationController
  before_action :current_user
  def index
    #choose JS or ruby
    #fade out
    #ajax call 
    #
  end
 
  def create
    level = @current_user.level.to_s
    strategy = "kyu_#{level}_workout"
    language = params["language"]
    request = Typhoeus::Request.new(
      "https://www.codewars.com/api/v1/code-challenges/#{language}/train",
      method: :post,
      params: { stratgey: strategy },
      headers: { Authorization: "q-sizxUQz1x1tsnxuFnY", ContentType: "text/html;" }
    )
    response = request.run
    @result = JSON.parse(response.response_body)
    @setup = @result["session"]["setup"]
    projectId = @result["session"]["projectId"]
    solutionId = @result["session"]["solutionId"]

    @katum = Katum.create({ solutionId: solutionId,
              projectId: projectId });
    @current_user.kata << @katum
    render json: {description: @result["description"].gsub(/[```]/, ""), setup: @result["session"]["setup"]}
  end

  def submit
    solutionId = @current_user.kata.last.solutionId
    projectId = @current_user.kata.last.projectId
    answer = params["answer"]
     request = Typhoeus::Request.new(
      "https://www.codewars.com/api/v1/code-challenges/projects/#{projectId}/solutions/#{solutionId}/attempt",
      method: :post,
      params: { code: answer, output_format: "raw"},
      headers: { Authorization: "q-sizxUQz1x1tsnxuFnY", ContentType: "text/html;" }
    )
    response = request.run
    @result = JSON.parse(response.response_body)

    request = Typhoeus::Request.new(
      "https://www.codewars.com/api/v1/code-challenges/projects/#{projectId}/solutions/#{solutionId}/attempt",
      method: :post,
      params: { code: answer, output_format: "raw"},
      headers: { Authorization: "q-sizxUQz1x1tsnxuFnY", ContentType: "text/html;" }
    )
    response = request.run
    @result = JSON.parse(response.response_body)
    dmid = @result["dmid"]
    deferred(dmid)
    sleep 5
    puts @result_deferred
    render json: @result_deferred 
  end

  def deferred(para)
    @result_deferred
    scheduler = Rufus::Scheduler.new
    scheduler.in '3s' do
      request_deferred = Typhoeus::Request.new(
        "https://www.codewars.com/api/v1/deferred/#{para}",
        method: :get,
        headers: { Authorization: "q-sizxUQz1x1tsnxuFnY", ContentType: "text/html;" }
      )
      @response_deferred = request_deferred.run
      @result_deferred = JSON.parse(@response_deferred.response_body)
    end
      @result_deferred
  end

  def game_plan
    
  end

  private

  def kata_params
    params.require(:katum).permit(:language, :answer)
  end

end

app/controllers/resets_controller.rb
class ResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user
      user.generate_password_reset_token!
      Reset.password_reset(user).deliver_now
      redirect_to home_path, notice: "Email sent"
    else
      flash.now[:alert] = "Email not found"
      render :new
    end
  end

  def edit
    @user = User.find_by(password_reset_token: params[:id])
    if @user
    else
      redirect_to home_path, alert: "Invalid reset token"
    end
  end

  def update
    @user = User.find_by(password_reset_token: params[:id])
    if params[:user][:password].present?
      if @user && @user.update(user_params)
        @user.update(password_reset_token: nil)
        session[:user_id] = @user.id
        redirect_to home_path, flash: {success: "Password updated."}
      else
        flash.now[:notice] = "Password reset token not found."
        render :edit
      end
    else
      flash.now[:alert] = "Please enter a password"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def signup
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to game_plan_path
    else
      render :signup
    end
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user && found_user.authenticate(params[:password])
        session[:user_id] = found_user.id
        redirect_to game_plan_path
      else
        flash[:alert] = "username / password combination is invalid"
        redirect_to home_path
      end
    else
      flash[:alert] = "please enter username and password"
      redirect_to home_path
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to home_path
  end

  def account_info
  end

  private

  def user_params
    params.require(:user).permit(:username,:password, :password_confirmation, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kata_helper.rb
module KataHelper
end

app/helpers/resets_helper.rb
module ResetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kata/game_plan.html.erb
<div class="gamePlan col-md-8 col-md-offset-2">
  <h1 style="color: #f9423a">Game Plan</h1><br><br>
  <h4>There are 8 levels, 8 being the highest, you are going to start with 1.</h4>
  <h4>There are 5 questions for each level. After successfully complete 5 challenges for each level, you are going to be bumped up to the next one.</h4>
  <h4>You can skip questions if you get stuck. If you skip 3 questions for one level, you are going to be down-graded by one level.</h4>
  <h4>You can try submitting your answer as many times as you want, there's no limit in that.</h4>
  <h4>Check your level and the number of completed challenges anytime in <%= link_to "Account Information", account_info_path %></h4><br><br>
  <%= button_to "Got it, now take me to the real stuff!", coding_challenges_path, method: :get, class:"btn btn-lg btn-success center-block" %>
</div>

app/views/kata/index.html.erb
<span class="col-md-offset-2 col-md-4 language_selection">
<h2>What Are You in the Mood for?</h2>
<br>
<%= form_tag coding_challenges_path do%>
  <span id='language'>
  <span class='language_button'>
  <%= submit_tag "ruby", class: 'btn btn-md btn-default' %>
  </span>
  <%= submit_tag "javascript", class: 'btn btn-md btn-default' %> 
  </span>
<% end %>
</span> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCodewars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

</head>
<body class="body-background">

<nav class="navbar navbar-default" id='navbar'>
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >AI App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Coding Challenges', coding_challenges_path %></li>
        <li><%= link_to 'Game Plan', game_plan_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User Info <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a id='dropDownColor' href="NEED TO CREATE THIS PAGE">Account Information</a></li>
            <li><%= link_to "Logout", logout_path, method: :delete, id: "dropDownColor" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="text-center">
  <% flash.each do |key, value| %>
        <% if key == "notice" %>
          <%= content_tag :div, value, class: "error" %>
        <% elsif key == "alert" %>
          <%= content_tag :div, value, class: "error" %>
        <% else %>
          <%= content_tag :div, value, class: "error" %>
        <% end %>
      <% end %>  
</div>

<div id="message" class="text-center"></div>

<%= yield %>

</body>
</html>

app/views/reset/password_reset.html.erb
<p>Hi <%=@user.email %>,</p>

<p> You can reset your password <%= link_to "here", edit_reset_url(@user.password_reset_token) %></p>

app/views/reset/password_reset.text.erb
Reset#password_reset

<%= @greeting %>, find me in app/views/reset/password_reset.text.erb

app/views/reset/welcome_account.html.erb
<p>Hi <%=@user.email %>,</p>

<p> Thank you for signing up for AI App! :)</p>

app/views/resets/edit.html.erb
<div class='col-md-4 col-md-offset-2'>
  <div class='jumbotron' id='signupForm'>
    <%= form_for :user, url:password_reset_path(@user.password_reset_token), method: :patch do |f|%>
    <h3>Change Your Password</h3><br>  
    <div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, autofocus: true%>
    </div>
    <div class='form-group'>
    <%= label_tag :password %>
    <%= password_field_tag :password, params[:password], class: 'form-control'%>
    </div>
    <%= f.submit "Reset Password"%> <br><br>
    <% end %>
  </div>
</div>

app/views/resets/new.html.erb
<div class='col-md-4 col-md-offset-2'>
  <div class='jumbotron' id='signupForm'>
    <%= form_tag resets_path do%>
    <h3>Enter Email To Reset Password</h3><br>  
    <div class='form-group'>
    <%= label_tag :email %> 
    <%= text_field_tag :email, params[:email], autofocus:true, class: 'form-control' %>
    </div><br>
    <%= submit_tag "Reset Password", class: 'btn btn-default' %> <br><br>
    <% end %>
  </div>
</div>

app/views/users/login.html.erb
<div class='col-md-4 col-md-offset-2'>
  <div class='jumbotron' id='signupForm'>
    <%= form_tag home_path do%>
    <h3>Welcome Back</h3><br>  
    <div class='form-group'>
    <%= label_tag :username %> 
    <%= text_field_tag :username, params[:username], autofocus:true, class: 'form-control' %>
    </div>
    <div class='form-group'>
    <%= label_tag :password %>
    <%= password_field_tag :password, params[:password], class: 'form-control'%>
    </div>
    <%= submit_tag "Log In", class: 'btn btn-default' %> <br><br>
    <%= link_to "Don't have an account? Sign up here", signup_path %><br><br>
    <%= link_to "Forgot your password? Reset here", new_reset_path %>
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<div class="error">
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
      <p><strong> * <%= error %></strong></p>
      <% end %>
  <% end %>  
</div>
  <div class='col-md-4 col-md-offset-2'>
    <div class='jumbotron' id='signupForm'>
      <%= form_for @user, url: signup_path do |f| %>
        <h3>Start the Journey Here</h3><br>    
        <div class='form-group'>
          <%= f.label :username %> 
          <%= f.text_field :username, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control'%>
        </div>
        <div class='form-group'>
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control'%>
        </div>
        <div class='form-group'>
          <%= f.label "confirm password" %>
          <%= f.password_field :password_confirmation, class: 'form-control'%>
        </div>
          <%= f.submit "Sign Up", class: 'btn btn-default'%> <br><br>
          <%= link_to "Returning user? Log in here", home_path %>
      <% end %>
      </div>